### ISSUE TITLE
windows wallet compilation

### ISSUE THREAD

**Issue by Hser2bio** [lpcproject/LightPayCoin#11]
Hi There! 

compiling windows qt, have the following issues

libbitcoin_zmq.a(libbitcoin_zmq_a-zmqnotificationinterface.o):zmqnotificationinterface.cpp:(.text+0x47d): undefined reference to `__imp_zmq_ctx_destroy'
libbitcoin_zmq.a(libbitcoin_zmq_a-zmqnotificationinterface.o):zmqnotificationinterface.cpp:(.text+0xaf6): undefined reference to `__imp_zmq_strerror'
libbitcoin_zmq.a(libbitcoin_zmq_a-zmqnotificationinterface.o):zmqnotificationinterface.cpp:(.text+0xbe5): undefined reference to `__imp_zmq_init'
libbitcoin_zmq.a(libbitcoin_zmq_a-zmqpublishnotifier.o):zmqpublishnotifier.cpp:(.text+0x1d): undefined reference to `__imp_zmq_msg_init_size'
libbitcoin_zmq.a(libbitcoin_zmq_a-zmqpublishnotifier.o):zmqpublishnotifier.cpp:(.text+0x3c): undefined reference to `__imp_zmq_msg_data'
libbitcoin_zmq.a(libbitcoin_zmq_a-zmqpublishnotifier.o):zmqpublishnotifier.cpp:(.text+0x58): undefined reference to `__imp_zmq_msg_send'
libbitcoin_zmq.a(libbitcoin_zmq_a-zmqpublishnotifier.o):zmqpublishnotifier.cpp:(.text+0x5f): undefined reference to `__imp_zmq_msg_close'
libbitcoin_zmq.a(libbitcoin_zmq_a-zmqpublishnotifier.o):zmqpublishnotifier.cpp:(.text+0x125): undefined reference to `__imp_zmq_msg_close'
libbitcoin_zmq.a(libbitcoin_zmq_a-zmqpublishnotifier.o):zmqpublishnotifier.cpp:(.text+0x7ef): undefined reference to `__imp_zmq_setsockopt'
libbitcoin_zmq.a(libbitcoin_zmq_a-zmqpublishnotifier.o):zmqpublishnotifier.cpp:(.text+0x7f9): undefined reference to `__imp_zmq_close'
libbitcoin_zmq.a(libbitcoin_zmq_a-zmqpublishnotifier.o):zmqpublishnotifier.cpp:(.text+0xe8a): undefined reference to `__imp_zmq_socket'
libbitcoin_zmq.a(libbitcoin_zmq_a-zmqpublishnotifier.o):zmqpublishnotifier.cpp:(.text+0xea4): undefined reference to `__imp_zmq_bind'
libbitcoin_zmq.a(libbitcoin_zmq_a-zmqpublishnotifier.o):zmqpublishnotifier.cpp:(.text+0xf39): undefined reference to `__imp_zmq_close'

any idea? i used to compile others pivx fork with no problem. 

thanks

**Comment by Hser2bio** [comment]
im fixed 

sorry!

**Comment by Xjasz** [comment]
Hey ReeCore may I ask what the issue was?  I'm experiencing the same problem

**Comment by Hser2bio** [comment]
Yes. Due depends are not the libs that ask wallet. Need compile manually

**Comment by Xjasz** [comment]
I'm not sure what you mean?  I'm doing a gitian build for windows.  Should I going into the project and run a make and then do a gitian build?

**Comment by Hser2bio** [comment]
Hi! 

Mean that this error is due when you are compiling windows wallet the depends folder of github are diferent than walllet needs.
