### ISSUE TITLE
Notice of Copyright/License Violation

### ISSUE THREAD

**Issue by Fuzzbawls** [lpcproject/LightPayCoin#7]
This is a notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license has been modified to explicitely exclude the PIVX developers' copyright.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository.

**Comment by onestan2** [comment]
No intent to violate.  I'll take a look and update now.

**Comment by onestan2** [comment]
Pull request is open and will be included in the next merge, which will happen usually within 24 hrs. 
https://github.com/lpcproject/LightPayCoin/pull/8

**Comment by lpcproject** [comment]
Request "pull requests" is completed.

**Comment by Fuzzbawls** [comment]
Thank you for your quick resolution to this issue.
